### ISSUE TITLE
Замечания по работе№1

### ISSUE THREAD

**Issue by AndriiLitvin** [yooloko/yooloko.github.io#1]
Нет картинки и на ней border-radius, отступы не соответствуют макету https://raw.githubusercontent.com/goit-fe/markup_fe2o/master/lesson_01/homework1.png
Вместо < hr > сделай блоку border-bottom

**Comment by AndriiLitvin** [comment]
Визуально
http://joxi.ru/J2blgP1FkMlyr6
1)нет бордеров
2) отступы

Код:
1)Названия классов должны быть говорящие.(чтоб программист мог понять без контента что там должно быть)

**Comment by AndriiLitvin** [comment]
!!!!! Переделай, чтоб я мог тебе зачет поставить

**Comment by yooloko** [comment]
lesson1 исправлено согласно замечаниям

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
