### ISSUE TITLE
Замечания по работе №3

### ISSUE THREAD

**Issue by AndriiLitvin** [yooloko/yooloko.github.io#2]
http://joxi.ru/EA4vLykFJQP9mb
1) нет картинок
2)от нижнего меню отступ должен быть
3)Font-style  другой
4)В левой менюшке шрифт больше и нужно сделать чтоб при наведении на весь блок надпись смещалась а не при наведении на текст и смещение было в право а не влево
5)  < div class="all"> - не информативно. что значит all что все. называй либо wrapper либо container

**Comment by yooloko** [comment]
lesson3 исправлено согласно замечаниям

**Comment by AndriiLitvin** [comment]
НЕ все. там у тебя в левой менюшке не такая реакция на ховер. нужно чтоб при наведении смещался текст вправо а у тебя влево

**Comment by yooloko** [comment]
lesson3 исправлено согласно замечаниям

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
